import { BoxType } from "../types/boxTypes";
export const predefinedBoxTypes: BoxType[] = [
    {
      name: 'Small Box',
      refId: 1,
      price: 500, 
      weightTare: 0.44, 
      weightMax: 4.41, 
      dimensions: {
        x: 11.81, 
        y: 7.87, 
        z: 5.91,
      },
    
      reservedSpace: 0.1,
      itemsPerBoxMax: 10,
      itemSetsPerBoxMax: 5,
    },
    {
      name: 'Medium Box',
      refId: 2,
      price: 800,
      weightTare: 0.88, 
      weightMax: 11.02, 
      dimensions: {
        x: 15.75, 
        y: 11.81, 
        z: 7.87, 
      },
  
      reservedSpace: 0.1,
      itemsPerBoxMax: 20,
      itemSetsPerBoxMax: 10,
    },
    {
      name: 'Large Box',
      refId: 3,
      price: 1200,
      weightTare: 1.32, 
      weightMax: 22.05, 
      dimensions: {
        x: 19.69, 
        y: 15.75, 
        z: 11.81, 
      },
  
      reservedSpace: 0.2,
      itemsPerBoxMax: 30,
      itemSetsPerBoxMax: 15,
    },
    {
      name: 'Extra Large Box',
      refId: 4,
      price: 1500,
      weightTare: 1.76, 
      weightMax: 33.07, 
      dimensions: {
        x: 23.62,
        y: 19.69, 
        z: 15.75, 
      },
  
      reservedSpace: 0.2,
      itemsPerBoxMax: 50,
      itemSetsPerBoxMax: 20,
    },
    {
      name: 'Flat Box',
      refId: 5,
      price: 400,
      weightTare: 0.33, 
      weightMax: 3.31, 
      dimensions: {
        x: 11.81, 
        y: 11.81, 
        z: 1.97, 
      },
      reservedSpace: 0.05,
      itemsPerBoxMax: 5,
      itemSetsPerBoxMax: 3,
    },
    {
      name: 'Tall Box',
      refId: 6,
      price: 1000,
      weightTare: 1.1, 
      weightMax: 17.64, 
      dimensions: {
        x: 11.81,
        y: 11.81, 
        z: 23.62, 
      },
      reservedSpace: 0.15,
      itemsPerBoxMax: 15,
      itemSetsPerBoxMax: 10,
    },
    {
      name: 'Heavy Duty Box',
      refId: 7,
      price: 2000,
      weightTare: 2.2, 
      weightMax: 44.09, 
      dimensions: {
        x: 27.56,
        y: 23.62,
        z: 19.69, 
      },
      reservedSpace: 0.25,
      itemsPerBoxMax: 40,
      itemSetsPerBoxMax: 25,
    },
    {
      name: 'Compact Box',
      refId: 8,
      price: 600,
      weightTare: 0.55, 
      weightMax: 6.61, 
      dimensions: {
        x: 9.84, 
        y: 7.87, 
        z: 7.87, 
      },
      reservedSpace: 0.1,
      itemsPerBoxMax: 8,
      itemSetsPerBoxMax: 4,
    },
  ];